# This is a basic workflow to help you get started with Actions
name: Firebase App Distribution (Debug)

on:
  push:
    branches:
      - staging

jobs:
  build-and-distribute:
    name: Build Debug APK & Distribute
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout
        uses: actions/checkout@v4

      # Set up JDK
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'

      # Set up Gradle cache
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3

      # Make Gradle executable
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # Build Debug APK
      - name: Build Debug APK
        run: ./gradlew assembleDebug

      # Install Firebase CLI
      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      # Upload to Firebase App Distribution
      - name: Distribute Debug APK to Firebase
        run: |
          firebase appdistribution:distribute app/build/outputs/apk/debug/app-debug.apk \
            --app <com.devyoussef.sahety> \
            --groups "Sahety" \
            --token ${{ secrets.FIREBASE_TOKEN }}
